openapi: 3.0.3
info:
  title: ToDo API
  version: 1.0.0
  description: ToDo API
paths:
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - ht
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/tasks/:
    get:
      operationId: tasks_list
      description: |-
        ModelViewSet providing full CRUD for Local Tasks and
        integrating automatic bidirectional sync with Google Tasks.
      tags:
      - tasks
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LocalTask'
          description: ''
    post:
      operationId: tasks_create
      description: |-
        ModelViewSet providing full CRUD for Local Tasks and
        integrating automatic bidirectional sync with Google Tasks.
      tags:
      - tasks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocalTask'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LocalTask'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LocalTask'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocalTask'
          description: ''
  /api/tasks/{id}/:
    get:
      operationId: tasks_retrieve
      description: |-
        ModelViewSet providing full CRUD for Local Tasks and
        integrating automatic bidirectional sync with Google Tasks.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this local task.
        required: true
      tags:
      - tasks
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocalTask'
          description: ''
    put:
      operationId: tasks_update
      description: |-
        ModelViewSet providing full CRUD for Local Tasks and
        integrating automatic bidirectional sync with Google Tasks.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this local task.
        required: true
      tags:
      - tasks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocalTask'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LocalTask'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LocalTask'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocalTask'
          description: ''
    patch:
      operationId: tasks_partial_update
      description: |-
        ModelViewSet providing full CRUD for Local Tasks and
        integrating automatic bidirectional sync with Google Tasks.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this local task.
        required: true
      tags:
      - tasks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedLocalTask'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedLocalTask'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedLocalTask'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocalTask'
          description: ''
    delete:
      operationId: tasks_destroy
      description: |-
        ModelViewSet providing full CRUD for Local Tasks and
        integrating automatic bidirectional sync with Google Tasks.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this local task.
        required: true
      tags:
      - tasks
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/tasks/sync-google/:
    get:
      operationId: tasks_sync_google_retrieve
      description: 'Custom endpoint: GET /api/tasks/sync-google/ to pull external
        Google tasks.'
      tags:
      - tasks
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocalTask'
          description: ''
components:
  schemas:
    LocalTask:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        notes:
          type: string
          nullable: true
        is_completed:
          type: boolean
        google_task_id:
          type: string
          readOnly: true
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - google_task_id
      - id
      - title
      - updated_at
      - user
    PatchedLocalTask:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        notes:
          type: string
          nullable: true
        is_completed:
          type: boolean
        google_task_id:
          type: string
          readOnly: true
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
