# Generated by Django 6.1.1 on 2026-10-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0003_alter_studentmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='currentSemester',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
